### ISSUE TITLE
Does it support DS6.3?

### ISSUE THREAD

**Issue by lida2003** [Ending2015a/ByteTrack-DS6.4#1]
I'm using ubuntu 20.04 not 22.04. So my quesiton is if it's ok to use on jetpack 5.1.3 which is basedon L4T 35.6 ubuntu 20.4 OS?

**Comment by Ending2015a** [comment]
Hello, some APIs have changed since DeepStream 6.4.
For DeepStream <6.3, please refer to the [original code](https://github.com/ifzhang/ByteTrack/tree/main/deploy/DeepStream).

**Comment by lida2003** [comment]
@Ending2015a I didn't find `libByteTracker.so` , see log below.

[log.txt](https://github.com/user-attachments/files/18135089/log.txt)

EDIT: I didn't find any `libByteTracker` target in this repo also. 

Can you help to let me know where this file can be found.

Then I can use as README did.

```
[tracker]
enable=1
tracker-width=640
tracker-height=384
gpu-id=0
ll-lib-file=//opt/nvidia/deepstream/deepstream/lib/libByteTracker.so
enable-batch-process=1
```

**Comment by lida2003** [comment]
@Ending2015a Just ignore the `libByteTracker.so` issue. I got the wrong CPP dir.

It should be `deploy/DeepStream/`
